version: '3'

networks:
    app-network:
        driver: bridge

services:
    nginx:
        container_name: nginx
        hostname: nginx
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
        restart: always
        networks:
            - app-network


    api:
        container_name: api
        hostname: api
        image: node:10
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - app-network
